# Generated by Django 4.2.15 on 2024-10-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='aurthor',
            field=models.CharField(default='Untitled Post', max_length=255),
        ),
    ]
