# Generated by Django 4.2.15 on 2024-10-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blog_post_aurthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='aurthor',
            field=models.CharField(default='Your name here', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='blog_content',
            field=models.TextField(default='Your of your Post', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(default='Title of your Post', max_length=255),
        ),
    ]
