# Generated by Django 4.2.15 on 2024-10-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_blog_post_aurthor_alter_blog_post_blog_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='aurthor',
            new_name='author',
        ),
    ]
